const rolePermissions = {
  Owner: ["*"],
  Accountant: [
    "dashboard:read",
    "dsr:read",
    "reports:read",
    "backup:read",
    "forecourt:read",
    "tank:read",
    "device:read",
    "shift:read",
    "dayend:read",
    "inventory:read",
    "config:read",
    "settings:read",
    "export:create",
    "print:create",
  ],
  Manager: [
    "dashboard:read",
    "dsr:create",
    "dsr:read",
    "dsr:update",
    "reports:read",
    "backup:read",
    "forecourt:read",
    "forecourt:manage",
    "tank:read",
    "tank:manage",
    "device:read",
    "device:manage",
    "shift:read",
    "shift:manage",
    "dayend:read",
    "dayend:manage",
    "alarm:read",
    "alarm:manage",
    "inventory:read",
    "inventory:manage",
    "attendant:read",
    "attendant:manage",
    "config:read",
    "config:manage",
    "settings:read",
    "export:create",
    "print:create",
  ],
  Supervisor: [
    "dashboard:read",
    "dsr:create",
    "dsr:read",
    "dsr:update",
    "reports:read",
    "backup:read",
    "forecourt:read",
    "tank:read",
    "tank:manage",
    "device:read",
    "shift:read",
    "shift:manage",
    "dayend:read",
    "alarm:read",
    "alarm:manage",
    "inventory:read",
    "attendant:read",
    "config:read",
    "settings:read",
    "print:create",
  ],
  Operator: [
    "dashboard:read",
    "dsr:create",
    "dsr:read",
    "dsr:update",
    "backup:read",
    "forecourt:read",
    "tank:read",
    "device:read",
    "shift:read",
    "shift:manage",
    "alarm:read",
    "inventory:read",
    "attendant:read",
    "settings:read",
    "operations:validate",
  ],
  Auditor: [
    "dashboard:read",
    "dsr:read",
    "reports:read",
    "backup:read",
    "forecourt:read",
    "tank:read",
    "device:read",
    "shift:read",
    "dayend:read",
    "alarm:read",
    "inventory:read",
    "attendant:read",
    "config:read",
    "settings:read",
  ],
  ReadOnly: [
    "dashboard:read",
    "dsr:read",
    "reports:read",
    "backup:read",
    "forecourt:read",
    "tank:read",
    "device:read",
    "shift:read",
    "dayend:read",
    "alarm:read",
    "inventory:read",
    "attendant:read",
    "config:read",
    "settings:read",
  ],
};

const roles = Object.keys(rolePermissions);

const hasPermission = (role, permission) => {
  const permissions = rolePermissions[role] || [];
  return permissions.includes("*") || permissions.includes(permission);
};

module.exports = {
  roles,
  rolePermissions,
  hasPermission,
};
